# Generated by Django 3.0.4 on 2020-07-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zxc',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
