# Generated by Django 3.0.4 on 2020-07-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_type',
        ),
    ]
