# Generated by Django 3.0.4 on 2020-07-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
