# Generated by Django 3.0.4 on 2020-07-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('scheduled_deadline', models.DateTimeField()),
                ('real_deadline', models.DateTimeField()),
                ('task_status', models.CharField(choices=[('ca', 'canceled'), ('co', 'completed'), ('s', 'started')], default='s', max_length=2)),
            ],
        ),
    ]
