# Generated by Django 3.0.4 on 2020-07-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200710_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='list.Board'),
        ),
    ]
