# Generated by Django 3.0.4 on 2020-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_board_user_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='real_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='scheduled_deadline',
            field=models.DateField(),
        ),
    ]
