# Generated by Django 3.0.4 on 2020-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20200717_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('completed', 'completed'), ('started', 'started')], default='started', max_length=9),
        ),
    ]
