# Generated by Django 3.0.4 on 2020-07-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20200722_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
