# Generated by Django 3.0.4 on 2020-07-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20200722_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
    ]
