# Generated by Django 3.0.4 on 2020-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_remove_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
