# Generated by Django 3.0.4 on 2020-07-23 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_auto_20200722_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=15)),
                ('parent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Task')),
            ],
        ),
    ]
