# Generated by Django 3.0.4 on 2020-07-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0015_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='list.Task'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
