# Generated by Django 3.0.4 on 2020-07-23 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_auto_20200723_0609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
