# Generated by Django 3.0.4 on 2020-07-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=None, max_length=15)),
                ('parent_task', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='list.Task')),
            ],
        ),
    ]
