# Generated by Django 3.0.4 on 2020-07-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0018_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(default='#AAAAAA', max_length=7),
        ),
    ]
