# Generated by Django 3.0.4 on 2020-07-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0019_board_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('CANCELED', 'CANCELED'), ('COMPLETED', 'COMPLETED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('TODO', 'TODO')], default='STARTED', max_length=11),
        ),
    ]
