# Generated by Django 3.0.4 on 2020-07-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_auto_20200728_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='real_deadline',
            field=models.DateField(auto_now_add=True),
        ),
    ]
